# Generated by Django 6.0.5 on 2026-08-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='funcionario',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('email',), name='uniq_funcionario_por_email'),
        ),
    ]
