# Generated by Django 6.0.5 on 2026-09-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colaboradores", "0002_funcionario_uniq_funcionario_por_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="funcionario",
            name="codigo_funcionario_erp",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=125,
                null=True,
                verbose_name="Código ERP",
            ),
        ),
    ]
