# Generated by Django 6.0.5 on 2026-09-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colaboradores", "0003_funcionario_codigo_funcionario_erp"),
    ]

    operations = [
        migrations.AddField(
            model_name="unidadefabril",
            name="codigo_empresa_erp",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                unique=True,
                verbose_name="Código empresa ERP",
            ),
        ),
    ]
