# Generated by Django 6.0.5 on 2026-09-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colaboradores", "0004_unidadefabril_codigo_empresa_erp"),
    ]

    operations = [
        migrations.CreateModel(
            name="Departamento",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("descricao", models.CharField(max_length=125)),
                (
                    "descricao_normalizada",
                    models.CharField(editable=False, max_length=125, unique=True),
                ),
            ],
            options={
                "verbose_name": "Departamento",
                "verbose_name_plural": "Departamentos",
                "ordering": ["descricao"],
                "db_table": "departamento",
            },
        ),
        migrations.CreateModel(
            name="Secao",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("descricao", models.CharField(max_length=125)),
                (
                    "descricao_normalizada",
                    models.CharField(editable=False, max_length=125),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="secoes",
                        to="colaboradores.departamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seção",
                "verbose_name_plural": "Seções",
                "ordering": ["descricao"],
                "db_table": "secao",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("departamento", "descricao_normalizada"),
                        name="uniq_secao_por_departamento",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="funcionario",
            name="departamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="funcionarios",
                to="colaboradores.departamento",
            ),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="secao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="funcionarios",
                to="colaboradores.secao",
            ),
        ),
        migrations.AddConstraint(
            model_name="funcionario",
            constraint=models.UniqueConstraint(
                condition=(
                    models.Q(("unidade_fabril__isnull", False))
                    & models.Q(("codigo_funcionario_erp__isnull", False))
                    & ~models.Q(("codigo_funcionario_erp", ""))
                ),
                fields=("unidade_fabril", "codigo_funcionario_erp"),
                name="uniq_funcionario_codigo_erp_por_unidade",
            ),
        ),
    ]
