# Generated by Django 6.0.5 on 2026-09-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0005_departamento_secao_funcionario_catalogos'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='data_admissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de admissão'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_demissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de demissão'),
        ),
    ]
