# Generated by Django 6.0.5 on 2026-09-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0006_funcionario_data_admissao_funcionario_data_demissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='auth_source',
            field=models.CharField(choices=[('LOCAL', 'Local'), ('DIRECTORY', 'Active Directory')], default='LOCAL', max_length=10),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='directory_guid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
