# Generated by Django 6.0.5 on 2026-09-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0007_funcionario_auth_source_funcionario_directory_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='auth_source',
            field=models.CharField(choices=[('LOCAL', 'Local'), ('DIRECTORY', 'Active Directory')], default='DIRECTORY', max_length=10),
        ),
    ]
