# Generated by Django 6.0.5 on 2026-09-25 18:12

import colaboradores.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0008_alter_funcionario_auth_source'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='funcionario',
            managers=[
                ('objects', colaboradores.models.FuncionarioManager()),
            ],
        ),
    ]
