# Generated by Django 6.0.5 on 2026-10-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0009_alter_funcionario_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='pode_receber_reserva_manual',
            field=models.BooleanField(default=False, verbose_name='Pode receber reserva manual'),
        ),
    ]
