# Generated by Django 6.0.5 on 2026-07-16 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colaboradores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fechamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('total_km', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fechamentos_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fechamento',
                'verbose_name_plural': 'Fechamentos',
                'db_table': 'fechamento',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('km_inicial', models.PositiveIntegerField()),
                ('km_final', models.PositiveIntegerField()),
                ('km_percorrida', models.PositiveIntegerField(default=0, editable=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('centro_custo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viagens', to='colaboradores.centrocusto')),
                ('fechamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viagens', to='viagens.fechamento')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viagens', to=settings.AUTH_USER_MODEL)),
                ('lancada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viagens_lancadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Viagem',
                'verbose_name_plural': 'Viagens',
                'db_table': 'viagem',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FechamentoRateio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('km_percorrida', models.PositiveIntegerField(default=0)),
                ('percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('centro_custo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rateios', to='colaboradores.centrocusto')),
                ('fechamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rateios', to='viagens.fechamento')),
            ],
            options={
                'verbose_name': 'Rateio do Fechamento',
                'verbose_name_plural': 'Rateios do Fechamento',
                'db_table': 'fechamento_rateio',
                'ordering': ['-km_percorrida'],
                'constraints': [models.UniqueConstraint(fields=('fechamento', 'centro_custo'), name='uniq_rateio_por_centro_custo')],
            },
        ),
    ]
