# Generated by Django 6.0.5 on 2026-07-27 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('modelo', models.CharField(blank=True, default='', max_length=125)),
                ('marca', models.CharField(blank=True, default='', max_length=40)),
                ('km_atual', models.PositiveBigIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'db_table': 'veiculos',
                'ordering': ['modelo'],
            },
        ),
        migrations.AddField(
            model_name='viagem',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viagens', to='viagens.veiculo'),
        ),
    ]
