# Generated by Django 6.0.5 on 2026-08-07 14:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
        ('viagens', '0002_veiculo_viagem_veiculo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='viagem',
            constraint=models.CheckConstraint(condition=models.Q(('km_final__gt', models.F('km_inicial'))), name='km_final_gt_km_inicial'),
        ),
    ]
