# Generated by Django 6.0.5 on 2026-08-07 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0003_viagem_km_final_gt_km_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viagens', to='viagens.veiculo'),
        ),
    ]
