# Generated by Django 6.0.5 on 2026-08-10 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
        ('viagens', '0004_viagem_veiculo_obrigatorio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='viagem',
            name='km_final_gt_km_inicial',
            constraint=models.CheckConstraint(condition=models.Q(('km_final__gt', models.F('km_inicial'))), name='km_final_gt_km_inicial', violation_error_message='A quilometragem final deve ser maior que a inicial.'),
        ),
    ]
