# Generated by Django 6.0.5 on 2026-08-11 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0005_mensagem_da_constraint_km'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaViagem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('solicitante_nome', models.CharField(blank=True, default='', max_length=200)),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fim', models.TimeField(blank=True, null=True)),
                ('destino', models.CharField(blank=True, default='', max_length=200)),
                ('origem', models.CharField(choices=[('manual', 'Manual'), ('outlook', 'Outlook')], default='manual', max_length=20)),
                ('id_externo', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('lancada', 'Lançada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reserva de Viagem',
                'verbose_name_plural': 'Reservas de Viagem',
                'db_table': 'reserva_viagem',
                'ordering': ['data', 'hora_inicio', 'id'],
            },
        ),
        migrations.AddField(
            model_name='veiculo',
            name='email_recurso',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddConstraint(
            model_name='veiculo',
            constraint=models.UniqueConstraint(condition=models.Q(('email_recurso', ''), _negated=True), fields=('email_recurso',), name='uniq_veiculo_por_email_recurso'),
        ),
        migrations.AddField(
            model_name='reservaviagem',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservaviagem',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='viagens.veiculo'),
        ),
        migrations.AddField(
            model_name='reservaviagem',
            name='viagem',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserva', to='viagens.viagem'),
        ),
        migrations.AddIndex(
            model_name='reservaviagem',
            index=models.Index(fields=['data', 'status'], name='idx_reserva_data_status'),
        ),
        migrations.AddConstraint(
            model_name='reservaviagem',
            constraint=models.UniqueConstraint(condition=models.Q(('id_externo', ''), _negated=True), fields=('origem', 'id_externo'), name='uniq_reserva_por_evento_externo'),
        ),
    ]
