# Generated by Django 6.0.5 on 2026-08-12 18:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
        ('viagens', '0006_reserva_viagem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='viagem',
            name='km_final_gt_km_inicial',
        ),
        migrations.AlterField(
            model_name='viagem',
            name='km_final',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='viagem',
            constraint=models.CheckConstraint(condition=models.Q(('km_final__isnull', True), ('km_final__gt', models.F('km_inicial')), _connector='OR'), name='km_final_gt_km_inicial', violation_error_message='A quilometragem final deve ser maior que a inicial.'),
        ),
    ]
