# Generated by Django 6.0.5 on 2026-08-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0007_viagem_em_andamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaviagem',
            name='solicitante_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
