# Generated by Django 6.0.5 on 2026-08-13 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0008_reserva_solicitante_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fechamento',
            options={'ordering': ['-criado_em'], 'permissions': [('realizar_fechamento', 'Pode fechar períodos e ver o histórico')], 'verbose_name': 'Fechamento', 'verbose_name_plural': 'Fechamentos'},
        ),
        migrations.AlterModelOptions(
            name='reservaviagem',
            options={'ordering': ['data', 'hora_inicio', 'id'], 'permissions': [('gerenciar_reservas', 'Pode criar reservas e sincronizar com o Outlook')], 'verbose_name': 'Reserva de Viagem', 'verbose_name_plural': 'Reservas de Viagem'},
        ),
        migrations.AlterModelOptions(
            name='viagem',
            options={'ordering': ['-data', '-id'], 'permissions': [('lancar_viagem', 'Pode lançar viagens e registrar chegadas')], 'verbose_name': 'Viagem', 'verbose_name_plural': 'Viagens'},
        ),
    ]
